linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - vet

linters-settings:
  goimports:
    local-prefixes: github.com/Xelon-AG/xelon-sdk-go

output:
  formats:
    - format: tab
  show-stats: true

run:
  timeout: 10m
