linters:
  disable-all: true
  enable:
    - durationcheck
    - exportloopref
    - godot
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/Xelon-AG/xelon-sdk-go

output:
  formats:
    - format: tab
  show-stats: true

run:
  timeout: 10m
