name: Release
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install tools
        run: make tools

      - name: Test
        run: make test

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release -f .github/goreleaser.yaml --clean
          distribution: goreleaser
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
