name: Build
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x ]

    name: unit tests (go ${{ matrix.go-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            .bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.go-version }}
          restore-keys: ${{ runner.os }}-go-

      - name: Lint
        run: make tools lint

      - name: Test
        run: make test
