name: Build
on:
  push:
    branches: [master]
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.16, 1.17, 1.18]

    name: unit tests (go ${{ matrix.go-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: .bin
          key: ${{ runner.os }}-linter-binaries

      - name: Lint
        run: make tools lint

      - name: Test
        run: make test
